/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov2_4dof_dist_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {8, 1, 1};
static const casadi_int casadi_s1[3] = {8, 8, 1};
static const casadi_int casadi_s2[3] = {8, 4, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};

/* bluerov2_4dof_dist_expl_vde_forw:(i0[8],i1[8x8],i2[8x4],i3[4],i4[8])->(o0[8],o1[8x8],o2[8x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34;
  a00=arg[0]? arg[0][3] : 0;
  a01=cos(a00);
  a02=arg[0]? arg[0][4] : 0;
  a03=(a01*a02);
  a00=sin(a00);
  a04=arg[0]? arg[0][5] : 0;
  a05=(a00*a04);
  a03=(a03-a05);
  a05=arg[4]? arg[4][0] : 0;
  a03=(a03+a05);
  if (res[0]!=0) res[0][0]=a03;
  a03=(a00*a02);
  a05=(a01*a04);
  a03=(a03+a05);
  a05=arg[4]? arg[4][1] : 0;
  a03=(a03+a05);
  if (res[0]!=0) res[0][1]=a03;
  a03=arg[0]? arg[0][6] : 0;
  a05=arg[4]? arg[4][2] : 0;
  a05=(a03+a05);
  if (res[0]!=0) res[0][2]=a05;
  a05=arg[0]? arg[0][7] : 0;
  a06=arg[4]? arg[4][3] : 0;
  a06=(a05+a06);
  if (res[0]!=0) res[0][3]=a06;
  a06=arg[3]? arg[3][0] : 0;
  a07=2.9899999999999999e+01;
  a08=(a07*a04);
  a09=(a08*a05);
  a06=(a06+a09);
  a09=-8.9999999999999997e-02;
  a10=-3.4960000000000001e+01;
  a11=casadi_fabs(a02);
  a11=(a10*a11);
  a09=(a09+a11);
  a11=(a09*a02);
  a06=(a06+a11);
  a11=14.;
  a06=(a06/a11);
  a11=arg[4]? arg[4][4] : 0;
  a06=(a06+a11);
  if (res[0]!=0) res[0][4]=a06;
  a06=arg[3]? arg[3][1] : 0;
  a11=-14.;
  a12=(a11*a02);
  a13=(a12*a05);
  a06=(a06+a13);
  a13=-2.6000000000000001e-01;
  a14=-1.0325000000000000e+02;
  a15=casadi_fabs(a04);
  a15=(a14*a15);
  a13=(a13+a15);
  a15=(a13*a04);
  a06=(a06+a15);
  a06=(a06/a07);
  a15=arg[4]? arg[4][5] : 0;
  a06=(a06+a15);
  if (res[0]!=0) res[0][5]=a06;
  a06=arg[3]? arg[3][2] : 0;
  a15=-1.9000000000000000e-01;
  a16=-7.4230000000000004e+01;
  a17=casadi_fabs(a03);
  a17=(a16*a17);
  a15=(a15+a17);
  a17=(a15*a03);
  a06=(a06+a17);
  a17=-3.6019999999999897e+00;
  a06=(a06+a17);
  a17=2.4700000000000003e+01;
  a06=(a06/a17);
  a17=arg[4]? arg[4][6] : 0;
  a06=(a06+a17);
  if (res[0]!=0) res[0][6]=a06;
  a06=arg[3]? arg[3][3] : 0;
  a17=-1.5900000000000000e+01;
  a18=(a17*a02);
  a19=(a18*a04);
  a06=(a06+a19);
  a19=-4.6399999999999997e+00;
  a20=-4.2999999999999999e-01;
  a21=casadi_fabs(a05);
  a21=(a20*a21);
  a19=(a19+a21);
  a21=(a19*a05);
  a06=(a06+a21);
  a21=5.2500000000000002e-01;
  a06=(a06/a21);
  a21=arg[4]? arg[4][7] : 0;
  a06=(a06+a21);
  if (res[0]!=0) res[0][7]=a06;
  a06=arg[1]? arg[1][4] : 0;
  a21=(a01*a06);
  a22=arg[1]? arg[1][3] : 0;
  a23=(a00*a22);
  a24=(a02*a23);
  a21=(a21-a24);
  a22=(a01*a22);
  a24=(a04*a22);
  a25=arg[1]? arg[1][5] : 0;
  a26=(a00*a25);
  a24=(a24+a26);
  a21=(a21-a24);
  if (res[1]!=0) res[1][0]=a21;
  a22=(a02*a22);
  a21=(a00*a06);
  a22=(a22+a21);
  a21=(a01*a25);
  a23=(a04*a23);
  a21=(a21-a23);
  a22=(a22+a21);
  if (res[1]!=0) res[1][1]=a22;
  a22=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][2]=a22;
  a21=arg[1]? arg[1][7] : 0;
  if (res[1]!=0) res[1][3]=a21;
  a23=7.1428571428571425e-02;
  a24=(a07*a25);
  a24=(a05*a24);
  a26=(a08*a21);
  a24=(a24+a26);
  a26=casadi_sign(a02);
  a27=(a26*a06);
  a27=(a10*a27);
  a27=(a02*a27);
  a28=(a09*a06);
  a27=(a27+a28);
  a24=(a24+a27);
  a24=(a23*a24);
  if (res[1]!=0) res[1][4]=a24;
  a24=3.3444816053511704e-02;
  a27=(a11*a06);
  a27=(a05*a27);
  a28=(a12*a21);
  a27=(a27+a28);
  a28=casadi_sign(a04);
  a29=(a28*a25);
  a29=(a14*a29);
  a29=(a04*a29);
  a30=(a13*a25);
  a29=(a29+a30);
  a27=(a27+a29);
  a27=(a24*a27);
  if (res[1]!=0) res[1][5]=a27;
  a27=4.0485829959514164e-02;
  a29=casadi_sign(a03);
  a30=(a29*a22);
  a30=(a16*a30);
  a30=(a03*a30);
  a22=(a15*a22);
  a30=(a30+a22);
  a30=(a27*a30);
  if (res[1]!=0) res[1][6]=a30;
  a30=1.9047619047619047e+00;
  a06=(a17*a06);
  a06=(a04*a06);
  a25=(a18*a25);
  a06=(a06+a25);
  a25=casadi_sign(a05);
  a22=(a25*a21);
  a22=(a20*a22);
  a22=(a05*a22);
  a21=(a19*a21);
  a22=(a22+a21);
  a06=(a06+a22);
  a06=(a30*a06);
  if (res[1]!=0) res[1][7]=a06;
  a06=arg[1]? arg[1][12] : 0;
  a22=(a01*a06);
  a21=arg[1]? arg[1][11] : 0;
  a31=(a00*a21);
  a32=(a02*a31);
  a22=(a22-a32);
  a21=(a01*a21);
  a32=(a04*a21);
  a33=arg[1]? arg[1][13] : 0;
  a34=(a00*a33);
  a32=(a32+a34);
  a22=(a22-a32);
  if (res[1]!=0) res[1][8]=a22;
  a21=(a02*a21);
  a22=(a00*a06);
  a21=(a21+a22);
  a22=(a01*a33);
  a31=(a04*a31);
  a22=(a22-a31);
  a21=(a21+a22);
  if (res[1]!=0) res[1][9]=a21;
  a21=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][10]=a21;
  a22=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][11]=a22;
  a31=(a07*a33);
  a31=(a05*a31);
  a32=(a08*a22);
  a31=(a31+a32);
  a32=(a26*a06);
  a32=(a10*a32);
  a32=(a02*a32);
  a34=(a09*a06);
  a32=(a32+a34);
  a31=(a31+a32);
  a31=(a23*a31);
  if (res[1]!=0) res[1][12]=a31;
  a31=(a11*a06);
  a31=(a05*a31);
  a32=(a12*a22);
  a31=(a31+a32);
  a32=(a28*a33);
  a32=(a14*a32);
  a32=(a04*a32);
  a34=(a13*a33);
  a32=(a32+a34);
  a31=(a31+a32);
  a31=(a24*a31);
  if (res[1]!=0) res[1][13]=a31;
  a31=(a29*a21);
  a31=(a16*a31);
  a31=(a03*a31);
  a21=(a15*a21);
  a31=(a31+a21);
  a31=(a27*a31);
  if (res[1]!=0) res[1][14]=a31;
  a06=(a17*a06);
  a06=(a04*a06);
  a33=(a18*a33);
  a06=(a06+a33);
  a33=(a25*a22);
  a33=(a20*a33);
  a33=(a05*a33);
  a22=(a19*a22);
  a33=(a33+a22);
  a06=(a06+a33);
  a06=(a30*a06);
  if (res[1]!=0) res[1][15]=a06;
  a06=arg[1]? arg[1][20] : 0;
  a33=(a01*a06);
  a22=arg[1]? arg[1][19] : 0;
  a31=(a00*a22);
  a21=(a02*a31);
  a33=(a33-a21);
  a22=(a01*a22);
  a21=(a04*a22);
  a32=arg[1]? arg[1][21] : 0;
  a34=(a00*a32);
  a21=(a21+a34);
  a33=(a33-a21);
  if (res[1]!=0) res[1][16]=a33;
  a22=(a02*a22);
  a33=(a00*a06);
  a22=(a22+a33);
  a33=(a01*a32);
  a31=(a04*a31);
  a33=(a33-a31);
  a22=(a22+a33);
  if (res[1]!=0) res[1][17]=a22;
  a22=arg[1]? arg[1][22] : 0;
  if (res[1]!=0) res[1][18]=a22;
  a33=arg[1]? arg[1][23] : 0;
  if (res[1]!=0) res[1][19]=a33;
  a31=(a07*a32);
  a31=(a05*a31);
  a21=(a08*a33);
  a31=(a31+a21);
  a21=(a26*a06);
  a21=(a10*a21);
  a21=(a02*a21);
  a34=(a09*a06);
  a21=(a21+a34);
  a31=(a31+a21);
  a31=(a23*a31);
  if (res[1]!=0) res[1][20]=a31;
  a31=(a11*a06);
  a31=(a05*a31);
  a21=(a12*a33);
  a31=(a31+a21);
  a21=(a28*a32);
  a21=(a14*a21);
  a21=(a04*a21);
  a34=(a13*a32);
  a21=(a21+a34);
  a31=(a31+a21);
  a31=(a24*a31);
  if (res[1]!=0) res[1][21]=a31;
  a31=(a29*a22);
  a31=(a16*a31);
  a31=(a03*a31);
  a22=(a15*a22);
  a31=(a31+a22);
  a31=(a27*a31);
  if (res[1]!=0) res[1][22]=a31;
  a06=(a17*a06);
  a06=(a04*a06);
  a32=(a18*a32);
  a06=(a06+a32);
  a32=(a25*a33);
  a32=(a20*a32);
  a32=(a05*a32);
  a33=(a19*a33);
  a32=(a32+a33);
  a06=(a06+a32);
  a06=(a30*a06);
  if (res[1]!=0) res[1][23]=a06;
  a06=arg[1]? arg[1][28] : 0;
  a32=(a01*a06);
  a33=arg[1]? arg[1][27] : 0;
  a31=(a00*a33);
  a22=(a02*a31);
  a32=(a32-a22);
  a33=(a01*a33);
  a22=(a04*a33);
  a21=arg[1]? arg[1][29] : 0;
  a34=(a00*a21);
  a22=(a22+a34);
  a32=(a32-a22);
  if (res[1]!=0) res[1][24]=a32;
  a33=(a02*a33);
  a32=(a00*a06);
  a33=(a33+a32);
  a32=(a01*a21);
  a31=(a04*a31);
  a32=(a32-a31);
  a33=(a33+a32);
  if (res[1]!=0) res[1][25]=a33;
  a33=arg[1]? arg[1][30] : 0;
  if (res[1]!=0) res[1][26]=a33;
  a32=arg[1]? arg[1][31] : 0;
  if (res[1]!=0) res[1][27]=a32;
  a31=(a07*a21);
  a31=(a05*a31);
  a22=(a08*a32);
  a31=(a31+a22);
  a22=(a26*a06);
  a22=(a10*a22);
  a22=(a02*a22);
  a34=(a09*a06);
  a22=(a22+a34);
  a31=(a31+a22);
  a31=(a23*a31);
  if (res[1]!=0) res[1][28]=a31;
  a31=(a11*a06);
  a31=(a05*a31);
  a22=(a12*a32);
  a31=(a31+a22);
  a22=(a28*a21);
  a22=(a14*a22);
  a22=(a04*a22);
  a34=(a13*a21);
  a22=(a22+a34);
  a31=(a31+a22);
  a31=(a24*a31);
  if (res[1]!=0) res[1][29]=a31;
  a31=(a29*a33);
  a31=(a16*a31);
  a31=(a03*a31);
  a33=(a15*a33);
  a31=(a31+a33);
  a31=(a27*a31);
  if (res[1]!=0) res[1][30]=a31;
  a06=(a17*a06);
  a06=(a04*a06);
  a21=(a18*a21);
  a06=(a06+a21);
  a21=(a25*a32);
  a21=(a20*a21);
  a21=(a05*a21);
  a32=(a19*a32);
  a21=(a21+a32);
  a06=(a06+a21);
  a06=(a30*a06);
  if (res[1]!=0) res[1][31]=a06;
  a06=arg[1]? arg[1][36] : 0;
  a21=(a01*a06);
  a32=arg[1]? arg[1][35] : 0;
  a31=(a00*a32);
  a33=(a02*a31);
  a21=(a21-a33);
  a32=(a01*a32);
  a33=(a04*a32);
  a22=arg[1]? arg[1][37] : 0;
  a34=(a00*a22);
  a33=(a33+a34);
  a21=(a21-a33);
  if (res[1]!=0) res[1][32]=a21;
  a32=(a02*a32);
  a21=(a00*a06);
  a32=(a32+a21);
  a21=(a01*a22);
  a31=(a04*a31);
  a21=(a21-a31);
  a32=(a32+a21);
  if (res[1]!=0) res[1][33]=a32;
  a32=arg[1]? arg[1][38] : 0;
  if (res[1]!=0) res[1][34]=a32;
  a21=arg[1]? arg[1][39] : 0;
  if (res[1]!=0) res[1][35]=a21;
  a31=(a07*a22);
  a31=(a05*a31);
  a33=(a08*a21);
  a31=(a31+a33);
  a33=(a26*a06);
  a33=(a10*a33);
  a33=(a02*a33);
  a34=(a09*a06);
  a33=(a33+a34);
  a31=(a31+a33);
  a31=(a23*a31);
  if (res[1]!=0) res[1][36]=a31;
  a31=(a11*a06);
  a31=(a05*a31);
  a33=(a12*a21);
  a31=(a31+a33);
  a33=(a28*a22);
  a33=(a14*a33);
  a33=(a04*a33);
  a34=(a13*a22);
  a33=(a33+a34);
  a31=(a31+a33);
  a31=(a24*a31);
  if (res[1]!=0) res[1][37]=a31;
  a31=(a29*a32);
  a31=(a16*a31);
  a31=(a03*a31);
  a32=(a15*a32);
  a31=(a31+a32);
  a31=(a27*a31);
  if (res[1]!=0) res[1][38]=a31;
  a06=(a17*a06);
  a06=(a04*a06);
  a22=(a18*a22);
  a06=(a06+a22);
  a22=(a25*a21);
  a22=(a20*a22);
  a22=(a05*a22);
  a21=(a19*a21);
  a22=(a22+a21);
  a06=(a06+a22);
  a06=(a30*a06);
  if (res[1]!=0) res[1][39]=a06;
  a06=arg[1]? arg[1][44] : 0;
  a22=(a01*a06);
  a21=arg[1]? arg[1][43] : 0;
  a31=(a00*a21);
  a32=(a02*a31);
  a22=(a22-a32);
  a21=(a01*a21);
  a32=(a04*a21);
  a33=arg[1]? arg[1][45] : 0;
  a34=(a00*a33);
  a32=(a32+a34);
  a22=(a22-a32);
  if (res[1]!=0) res[1][40]=a22;
  a21=(a02*a21);
  a22=(a00*a06);
  a21=(a21+a22);
  a22=(a01*a33);
  a31=(a04*a31);
  a22=(a22-a31);
  a21=(a21+a22);
  if (res[1]!=0) res[1][41]=a21;
  a21=arg[1]? arg[1][46] : 0;
  if (res[1]!=0) res[1][42]=a21;
  a22=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][43]=a22;
  a31=(a07*a33);
  a31=(a05*a31);
  a32=(a08*a22);
  a31=(a31+a32);
  a32=(a26*a06);
  a32=(a10*a32);
  a32=(a02*a32);
  a34=(a09*a06);
  a32=(a32+a34);
  a31=(a31+a32);
  a31=(a23*a31);
  if (res[1]!=0) res[1][44]=a31;
  a31=(a11*a06);
  a31=(a05*a31);
  a32=(a12*a22);
  a31=(a31+a32);
  a32=(a28*a33);
  a32=(a14*a32);
  a32=(a04*a32);
  a34=(a13*a33);
  a32=(a32+a34);
  a31=(a31+a32);
  a31=(a24*a31);
  if (res[1]!=0) res[1][45]=a31;
  a31=(a29*a21);
  a31=(a16*a31);
  a31=(a03*a31);
  a21=(a15*a21);
  a31=(a31+a21);
  a31=(a27*a31);
  if (res[1]!=0) res[1][46]=a31;
  a06=(a17*a06);
  a06=(a04*a06);
  a33=(a18*a33);
  a06=(a06+a33);
  a33=(a25*a22);
  a33=(a20*a33);
  a33=(a05*a33);
  a22=(a19*a22);
  a33=(a33+a22);
  a06=(a06+a33);
  a06=(a30*a06);
  if (res[1]!=0) res[1][47]=a06;
  a06=arg[1]? arg[1][52] : 0;
  a33=(a01*a06);
  a22=arg[1]? arg[1][51] : 0;
  a31=(a00*a22);
  a21=(a02*a31);
  a33=(a33-a21);
  a22=(a01*a22);
  a21=(a04*a22);
  a32=arg[1]? arg[1][53] : 0;
  a34=(a00*a32);
  a21=(a21+a34);
  a33=(a33-a21);
  if (res[1]!=0) res[1][48]=a33;
  a22=(a02*a22);
  a33=(a00*a06);
  a22=(a22+a33);
  a33=(a01*a32);
  a31=(a04*a31);
  a33=(a33-a31);
  a22=(a22+a33);
  if (res[1]!=0) res[1][49]=a22;
  a22=arg[1]? arg[1][54] : 0;
  if (res[1]!=0) res[1][50]=a22;
  a33=arg[1]? arg[1][55] : 0;
  if (res[1]!=0) res[1][51]=a33;
  a31=(a07*a32);
  a31=(a05*a31);
  a21=(a08*a33);
  a31=(a31+a21);
  a21=(a26*a06);
  a21=(a10*a21);
  a21=(a02*a21);
  a34=(a09*a06);
  a21=(a21+a34);
  a31=(a31+a21);
  a31=(a23*a31);
  if (res[1]!=0) res[1][52]=a31;
  a31=(a11*a06);
  a31=(a05*a31);
  a21=(a12*a33);
  a31=(a31+a21);
  a21=(a28*a32);
  a21=(a14*a21);
  a21=(a04*a21);
  a34=(a13*a32);
  a21=(a21+a34);
  a31=(a31+a21);
  a31=(a24*a31);
  if (res[1]!=0) res[1][53]=a31;
  a31=(a29*a22);
  a31=(a16*a31);
  a31=(a03*a31);
  a22=(a15*a22);
  a31=(a31+a22);
  a31=(a27*a31);
  if (res[1]!=0) res[1][54]=a31;
  a06=(a17*a06);
  a06=(a04*a06);
  a32=(a18*a32);
  a06=(a06+a32);
  a32=(a25*a33);
  a32=(a20*a32);
  a32=(a05*a32);
  a33=(a19*a33);
  a32=(a32+a33);
  a06=(a06+a32);
  a06=(a30*a06);
  if (res[1]!=0) res[1][55]=a06;
  a06=arg[1]? arg[1][60] : 0;
  a32=(a01*a06);
  a33=arg[1]? arg[1][59] : 0;
  a31=(a00*a33);
  a22=(a02*a31);
  a32=(a32-a22);
  a33=(a01*a33);
  a22=(a04*a33);
  a21=arg[1]? arg[1][61] : 0;
  a34=(a00*a21);
  a22=(a22+a34);
  a32=(a32-a22);
  if (res[1]!=0) res[1][56]=a32;
  a33=(a02*a33);
  a32=(a00*a06);
  a33=(a33+a32);
  a32=(a01*a21);
  a31=(a04*a31);
  a32=(a32-a31);
  a33=(a33+a32);
  if (res[1]!=0) res[1][57]=a33;
  a33=arg[1]? arg[1][62] : 0;
  if (res[1]!=0) res[1][58]=a33;
  a32=arg[1]? arg[1][63] : 0;
  if (res[1]!=0) res[1][59]=a32;
  a31=(a07*a21);
  a31=(a05*a31);
  a22=(a08*a32);
  a31=(a31+a22);
  a22=(a26*a06);
  a22=(a10*a22);
  a22=(a02*a22);
  a34=(a09*a06);
  a22=(a22+a34);
  a31=(a31+a22);
  a31=(a23*a31);
  if (res[1]!=0) res[1][60]=a31;
  a31=(a11*a06);
  a31=(a05*a31);
  a22=(a12*a32);
  a31=(a31+a22);
  a22=(a28*a21);
  a22=(a14*a22);
  a22=(a04*a22);
  a34=(a13*a21);
  a22=(a22+a34);
  a31=(a31+a22);
  a31=(a24*a31);
  if (res[1]!=0) res[1][61]=a31;
  a31=(a29*a33);
  a31=(a16*a31);
  a31=(a03*a31);
  a33=(a15*a33);
  a31=(a31+a33);
  a31=(a27*a31);
  if (res[1]!=0) res[1][62]=a31;
  a06=(a17*a06);
  a06=(a04*a06);
  a21=(a18*a21);
  a06=(a06+a21);
  a21=(a25*a32);
  a21=(a20*a21);
  a21=(a05*a21);
  a32=(a19*a32);
  a21=(a21+a32);
  a06=(a06+a21);
  a06=(a30*a06);
  if (res[1]!=0) res[1][63]=a06;
  a06=arg[2]? arg[2][4] : 0;
  a21=(a01*a06);
  a32=arg[2]? arg[2][3] : 0;
  a31=(a00*a32);
  a33=(a02*a31);
  a21=(a21-a33);
  a32=(a01*a32);
  a33=(a04*a32);
  a22=arg[2]? arg[2][5] : 0;
  a34=(a00*a22);
  a33=(a33+a34);
  a21=(a21-a33);
  if (res[2]!=0) res[2][0]=a21;
  a32=(a02*a32);
  a21=(a00*a06);
  a32=(a32+a21);
  a21=(a01*a22);
  a31=(a04*a31);
  a21=(a21-a31);
  a32=(a32+a21);
  if (res[2]!=0) res[2][1]=a32;
  a32=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][2]=a32;
  a21=arg[2]? arg[2][7] : 0;
  if (res[2]!=0) res[2][3]=a21;
  a31=(a07*a22);
  a31=(a05*a31);
  a33=(a08*a21);
  a31=(a31+a33);
  a33=(a26*a06);
  a33=(a10*a33);
  a33=(a02*a33);
  a34=(a09*a06);
  a33=(a33+a34);
  a31=(a31+a33);
  a31=(a23*a31);
  a31=(a23+a31);
  if (res[2]!=0) res[2][4]=a31;
  a31=(a11*a06);
  a31=(a05*a31);
  a33=(a12*a21);
  a31=(a31+a33);
  a33=(a28*a22);
  a33=(a14*a33);
  a33=(a04*a33);
  a34=(a13*a22);
  a33=(a33+a34);
  a31=(a31+a33);
  a31=(a24*a31);
  if (res[2]!=0) res[2][5]=a31;
  a31=(a29*a32);
  a31=(a16*a31);
  a31=(a03*a31);
  a32=(a15*a32);
  a31=(a31+a32);
  a31=(a27*a31);
  if (res[2]!=0) res[2][6]=a31;
  a06=(a17*a06);
  a06=(a04*a06);
  a22=(a18*a22);
  a06=(a06+a22);
  a22=(a25*a21);
  a22=(a20*a22);
  a22=(a05*a22);
  a21=(a19*a21);
  a22=(a22+a21);
  a06=(a06+a22);
  a06=(a30*a06);
  if (res[2]!=0) res[2][7]=a06;
  a06=arg[2]? arg[2][12] : 0;
  a22=(a01*a06);
  a21=arg[2]? arg[2][11] : 0;
  a31=(a00*a21);
  a32=(a02*a31);
  a22=(a22-a32);
  a21=(a01*a21);
  a32=(a04*a21);
  a33=arg[2]? arg[2][13] : 0;
  a34=(a00*a33);
  a32=(a32+a34);
  a22=(a22-a32);
  if (res[2]!=0) res[2][8]=a22;
  a21=(a02*a21);
  a22=(a00*a06);
  a21=(a21+a22);
  a22=(a01*a33);
  a31=(a04*a31);
  a22=(a22-a31);
  a21=(a21+a22);
  if (res[2]!=0) res[2][9]=a21;
  a21=arg[2]? arg[2][14] : 0;
  if (res[2]!=0) res[2][10]=a21;
  a22=arg[2]? arg[2][15] : 0;
  if (res[2]!=0) res[2][11]=a22;
  a31=(a07*a33);
  a31=(a05*a31);
  a32=(a08*a22);
  a31=(a31+a32);
  a32=(a26*a06);
  a32=(a10*a32);
  a32=(a02*a32);
  a34=(a09*a06);
  a32=(a32+a34);
  a31=(a31+a32);
  a31=(a23*a31);
  if (res[2]!=0) res[2][12]=a31;
  a31=(a11*a06);
  a31=(a05*a31);
  a32=(a12*a22);
  a31=(a31+a32);
  a32=(a28*a33);
  a32=(a14*a32);
  a32=(a04*a32);
  a34=(a13*a33);
  a32=(a32+a34);
  a31=(a31+a32);
  a31=(a24*a31);
  a31=(a24+a31);
  if (res[2]!=0) res[2][13]=a31;
  a31=(a29*a21);
  a31=(a16*a31);
  a31=(a03*a31);
  a21=(a15*a21);
  a31=(a31+a21);
  a31=(a27*a31);
  if (res[2]!=0) res[2][14]=a31;
  a06=(a17*a06);
  a06=(a04*a06);
  a33=(a18*a33);
  a06=(a06+a33);
  a33=(a25*a22);
  a33=(a20*a33);
  a33=(a05*a33);
  a22=(a19*a22);
  a33=(a33+a22);
  a06=(a06+a33);
  a06=(a30*a06);
  if (res[2]!=0) res[2][15]=a06;
  a06=arg[2]? arg[2][20] : 0;
  a33=(a01*a06);
  a22=arg[2]? arg[2][19] : 0;
  a31=(a00*a22);
  a21=(a02*a31);
  a33=(a33-a21);
  a22=(a01*a22);
  a21=(a04*a22);
  a32=arg[2]? arg[2][21] : 0;
  a34=(a00*a32);
  a21=(a21+a34);
  a33=(a33-a21);
  if (res[2]!=0) res[2][16]=a33;
  a22=(a02*a22);
  a33=(a00*a06);
  a22=(a22+a33);
  a33=(a01*a32);
  a31=(a04*a31);
  a33=(a33-a31);
  a22=(a22+a33);
  if (res[2]!=0) res[2][17]=a22;
  a22=arg[2]? arg[2][22] : 0;
  if (res[2]!=0) res[2][18]=a22;
  a33=arg[2]? arg[2][23] : 0;
  if (res[2]!=0) res[2][19]=a33;
  a31=(a07*a32);
  a31=(a05*a31);
  a21=(a08*a33);
  a31=(a31+a21);
  a21=(a26*a06);
  a21=(a10*a21);
  a21=(a02*a21);
  a34=(a09*a06);
  a21=(a21+a34);
  a31=(a31+a21);
  a31=(a23*a31);
  if (res[2]!=0) res[2][20]=a31;
  a31=(a11*a06);
  a31=(a05*a31);
  a21=(a12*a33);
  a31=(a31+a21);
  a21=(a28*a32);
  a21=(a14*a21);
  a21=(a04*a21);
  a34=(a13*a32);
  a21=(a21+a34);
  a31=(a31+a21);
  a31=(a24*a31);
  if (res[2]!=0) res[2][21]=a31;
  a31=(a29*a22);
  a31=(a16*a31);
  a31=(a03*a31);
  a22=(a15*a22);
  a31=(a31+a22);
  a31=(a27*a31);
  a31=(a27+a31);
  if (res[2]!=0) res[2][22]=a31;
  a06=(a17*a06);
  a06=(a04*a06);
  a32=(a18*a32);
  a06=(a06+a32);
  a32=(a25*a33);
  a32=(a20*a32);
  a32=(a05*a32);
  a33=(a19*a33);
  a32=(a32+a33);
  a06=(a06+a32);
  a06=(a30*a06);
  if (res[2]!=0) res[2][23]=a06;
  a06=arg[2]? arg[2][28] : 0;
  a32=(a01*a06);
  a33=arg[2]? arg[2][27] : 0;
  a31=(a00*a33);
  a22=(a02*a31);
  a32=(a32-a22);
  a33=(a01*a33);
  a22=(a04*a33);
  a21=arg[2]? arg[2][29] : 0;
  a34=(a00*a21);
  a22=(a22+a34);
  a32=(a32-a22);
  if (res[2]!=0) res[2][24]=a32;
  a33=(a02*a33);
  a00=(a00*a06);
  a33=(a33+a00);
  a01=(a01*a21);
  a31=(a04*a31);
  a01=(a01-a31);
  a33=(a33+a01);
  if (res[2]!=0) res[2][25]=a33;
  a33=arg[2]? arg[2][30] : 0;
  if (res[2]!=0) res[2][26]=a33;
  a01=arg[2]? arg[2][31] : 0;
  if (res[2]!=0) res[2][27]=a01;
  a07=(a07*a21);
  a07=(a05*a07);
  a08=(a08*a01);
  a07=(a07+a08);
  a26=(a26*a06);
  a10=(a10*a26);
  a02=(a02*a10);
  a09=(a09*a06);
  a02=(a02+a09);
  a07=(a07+a02);
  a23=(a23*a07);
  if (res[2]!=0) res[2][28]=a23;
  a11=(a11*a06);
  a11=(a05*a11);
  a12=(a12*a01);
  a11=(a11+a12);
  a28=(a28*a21);
  a14=(a14*a28);
  a14=(a04*a14);
  a13=(a13*a21);
  a14=(a14+a13);
  a11=(a11+a14);
  a24=(a24*a11);
  if (res[2]!=0) res[2][29]=a24;
  a29=(a29*a33);
  a16=(a16*a29);
  a03=(a03*a16);
  a15=(a15*a33);
  a03=(a03+a15);
  a27=(a27*a03);
  if (res[2]!=0) res[2][30]=a27;
  a17=(a17*a06);
  a04=(a04*a17);
  a18=(a18*a21);
  a04=(a04+a18);
  a25=(a25*a01);
  a20=(a20*a25);
  a05=(a05*a20);
  a19=(a19*a01);
  a05=(a05+a19);
  a04=(a04+a05);
  a04=(a30*a04);
  a30=(a30+a04);
  if (res[2]!=0) res[2][31]=a30;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_4dof_dist_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov2_4dof_dist_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_4dof_dist_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2_4dof_dist_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov2_4dof_dist_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2_4dof_dist_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov2_4dof_dist_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov2_4dof_dist_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov2_4dof_dist_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int bluerov2_4dof_dist_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real bluerov2_4dof_dist_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2_4dof_dist_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2_4dof_dist_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2_4dof_dist_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2_4dof_dist_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov2_4dof_dist_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_4dof_dist_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
